language: python
python:
- 3.5
rvm:
- 2.0.0
services:
- docker
before_install:
- gem update --system
- gem --version
- openssl aes-256-cbc -K $encrypted_d617236a007d_key -iv $encrypted_d617236a007d_iv -in Input_keystore.keystore.enc -out Input_keystore.keystore -d
- pip3 install dropbox

script:
- export OSGEO4A_SDK=opengisch/qfield-sdk:20190403
- docker pull ${OSGEO4A_SDK}
- docker run -v $(pwd):/usr/src/input -e "BUILD_FOLDER=build-${ARCH}" -e "ARCH=${ARCH}" -e "STOREPASS=${STOREPASS}" -e "KEYNAME=${KEYNAME}" -e "KEYPASS=${KEYPASS}" -e "VERSION=${TRAVIS_TAG}" ${OSGEO4A_SDK} /usr/src/input/scripts/docker-build.sh
- "./scripts/upload-artifacts.sh"
jobs:
  include:
  - stage: build
    name: build ARMv7
    env:
    - ARCH=armv7
