image: Visual Studio 2015
environment:
  global:
    GITHUB_TOKEN:
      secure: gqLWRiVUFKd+MsoevoouKEHG0tpvM9zhhSnCpzj9lRg4vcGq+ssWIG2m7kCbgLAC
    DROPBOX_TOKEN:
      secure: SbA10ZSj12UGtUP6o9r0gEATY+S3ZO6h0KhRZfZ3L2iM6Kx1T0gd+KgTD1D4C8ye0qKHbkRdCHxKwt5ETyo0iAK59b6UgRTbIUhmrvnWXIU=
    WINSDKTAG: win-4
    WINSDK: "https://www.dropbox.com/s/9l8zsx8snj4bz7r/input-sdk-win-x86_64-4.zip?dl=1"
    PYEXE: "C:\\Python36-x64\\python"

install:
  - "choco install wintail"
  - "%PYEXE% -m pip install dropbox"
  - "xcopy scripts\\ci\\config.pri app\\ /Y"
  - cmd: ".\\scripts\\download_sdk.cmd"
  - cmd: ".\\scripts\\build_win.cmd"
  - cmd: ".\\upload-artifacts.cmd"

build: off

skip_branch_with_pr: false