name: Auto Tests
on: [push]
env:
  TEST_MERGIN_URL: https://test.dev.cloudmergin.com/
  TEST_API_USERNAME: test_inputapp
  TEST_API_PASSWORD: ${{ secrets.MERGINTEST_API_PASSWORD }}
  QT_VERSION: 5.14.2
  QGIS_DEPS_VERSION: 0.5.4
  SDK_HASH: 2c855s4g55zmorx
  SDK_VERSION: 4

jobs:
  tests:
    if: github.repository == 'lutraconsulting/input'
    runs-on: macos-latest
    steps:
      - name: Checkout Input
        uses: actions/checkout@v2
        with:
          path: input

      - name: install brew deps
        run: |
          brew install lcov

      - name: Extract Mergin API_KEY
        env:
          MERGINSECRETS_DECRYPT_KEY: ${{ secrets.MERGINSECRETS_DECRYPT_KEY }}
        run: |
          cd input/app/
          /usr/local/opt/openssl@1.1/bin/openssl \
              aes-256-cbc -d \
              -in merginsecrets.cpp.enc \
              -out merginsecrets.cpp \
              -k "$MERGINSECRETS_DECRYPT_KEY" \
              -md md5

      - name: download input-sdk
        run: |
          ROOT=`pwd`
          wget https://www.dropbox.com/s/${SDK_HASH}/input-sdk-qt-${QT_VERSION}-deps-${QGIS_DEPS_VERSION}-mac-${SDK_VERSION}.tar.gz?dl=0
          mv $ROOT/input-sdk-qt-${QT_VERSION}-deps-${QGIS_DEPS_VERSION}-mac-${SDK_VERSION}.tar.gz?dl=0 $ROOT/input-sdk.tar.gz
          sudo mkdir -p /opt/INPUT
          sudo chown -R $USER /opt/INPUT
          mkdir -p /opt/INPUT/input-sdk-mac-$SDK_VERSION/stage/mac
          cd /opt/INPUT/input-sdk-mac-$SDK_VERSION/stage/mac
          tar -xvzf $ROOT/input-sdk.tar.gz
          mkdir -p /opt/INPUT/input-sdk-mac-${SDK_VERSION}/build/qgis/build-mac/output
          ln -s /opt/INPUT/input-sdk-mac-${SDK_VERSION}/stage/mac/QGIS.app/Contents/Frameworks/ /opt/INPUT/input-sdk-mac-${SDK_VERSION}/build/qgis/build-mac/output/lib

      - name: download qt
        run: |
          ROOT=`pwd`
          wget https://qgis.org/downloads/macos/deps/qt-${QT_VERSION}.tar.gz
          sudo mkdir -p /opt/Qt
          sudo chown -R $USER /opt/Qt
          mkdir -p /opt/Qt/${QT_VERSION}/clang_64
          cd /opt/Qt/${QT_VERSION}/clang_64
          tar -xvzf $ROOT/qt-${QT_VERSION}.tar.gz

      - name: download qgis-deps
        run: |
          ROOT=`pwd`
          wget https://qgis.org/downloads/macos/deps/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz
          sudo mkdir -p /opt/QGIS
          sudo chown -R $USER /opt/QGIS
          mkdir -p /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          cd /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/
          tar -xvzf $ROOT/qgis-deps-${QGIS_DEPS_VERSION}.tar.gz

      - name: build Input
        run: |
          cp input/scripts/ci/config.pri input/app/config.pri

          mkdir -p build-Input
          cd build-Input
          /opt/Qt/${QT_VERSION}/clang_64/bin/qmake \
            ../input/app/input.pro \
            CONFIG+=debug \
            CONFIG+=qtquickcompiler

          make -j $(sysctl -n hw.ncpu)
          install_name_tool -add_rpath /opt/QGIS/qgis-deps-${QGIS_DEPS_VERSION}/stage/lib/ Input.app/Contents/MacOS/Input
          install_name_tool -add_rpath /opt/INPUT/input-sdk-mac-${SDK_VERSION}/stage/mac/lib Input.app/Contents/MacOS/Input

      - name: run help links tests
        run: |
          cd build-Input/
          ./Input.app/Contents/MacOS/Input --testLinks

      - name: run mergin api tests
        run: |
          cd build-Input/
          ./Input.app/Contents/MacOS/Input --testMerginApi

      - name: run purchasing tests
        run: |
          cd build-Input/
          ./Input.app/Contents/MacOS/Input --testPurchasing

      - name: build lcov summary
        run: |
          cd build-Input
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '*/merginsecrets.cpp' '*/test/*' '/usr/*' '/Applications/*' '/opt/*' '*build-Input/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: build-Input/coverage.info

