name: QgsQuick
on: [push]
jobs:
  qgsquick_up_to_date:
    if: ( github.repository == 'lutraconsulting/input' ) && (!contains(github.event.head_commit.message, 'Translate '))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: download qgis
        run: |
          git clone https://github.com/qgis/QGIS.git --depth 1
          cd QGIS
          git fetch --depth 1 origin 1d17bf5bd35d7872f53c8e1c8b0a1e371616bf07
          git checkout FETCH_HEAD
          cd ..

      - name: run check the qgsquick is up-to-date
        run: |
          ./scripts/copy_qgsquick.bash QGIS/
